### ISSUE TITLE
老师白板上课模式功能怎么基于Demo修改?

### ISSUE THREAD

**Issue by tangbing** [tencentyun/TIC#10]
这个demo里面，是进入房间的人，只要打开摄像头，都显示摄像头画面，，但是实际场景是，老师用白板讲上课，那视频渲染显示是老师摄像头显示的画面，直接显示，怎么改呢？可以简略说一下步骤吗？比如，创建房间模式，是直播模式吗？

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，您可以修改进入房间时的参数  ，不要开启摄像头 不采集本地视频流
技术问题 欢迎交流 q2562367495注明来意
